### ISSUE TITLE
"Recent" view sometimes misses a slash in the directory path

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-drive#1127] opened 2018-08-24 13:37 UTC
Here the path is actually "/Factures/Netflix" not "/FactureNetflix". For some other bills the middle slash is present as expected.

![screenshot_20180824-153459](https://user-images.githubusercontent.com/3419050/44587538-8bb9e300-a7b3-11e8-815f-c25847aae0ea.png)

**Comment by cedricmessiant** [comment] 2019-01-07 13:14
I can't reproduce the bug and I think it has been fixed. @nicofrand please let us know if you still have an issue after the next release

**Comment by Crash--** [comment] 2019-09-09 12:24
It seems to be related to `MidEllipsis` https://github.com/cozy/cozy-drive/issues/1127

**Comment by Crash--** [comment] 2022-10-05 06:54
Should be fixed now (in fact since a few months but I didn't update the issue...)

**Closed by Crash--** 2022-10-05 06:54 UTC
Labels: bug, mobile
