### ISSUE TITLE
Cozy Drive seems to resync everything at start since 3.16

### ISSUE THREAD

**Issue by fred9176** [cozy/cozy-drive#1896] opened 2019-11-16 08:44 UTC
Hi,

Since Cozy Drive updated to 3.16 (actually, I'm in 3.16.1) in Win 10, it is very slow to be ready, like if it were rescanning all documents again and again. The title is continuously blinking between Ready and Peparing. This last for 5 minutes after it's ok.

And this happens everytime I start Cozy Drive (ie every time I start my computer).

My Cozy Drive contains about 8700 files.

Thank you for your help,

Fred

**Comment by y-lohse** [comment] 2019-11-18 09:30
Ping @taratatach

**Comment by taratatach** [comment] 2019-11-19 09:41
Hi @fred9176,

Thanks for reaching out. The blinking issue you're reporting sounds like the result of a change that was introduced in v3.16.1 and should be fixed in the upcoming release.
The time required for the app to get ready shouldn't have changed however (unless you've added a lot of new documents to your synchronized folder recently?) and I encourage you to contact support via the app itself (`Preferences` tab > `Send us a message`) as log info will be attached to your message and will help us in determining the cause of potential issues. It would be great if you could do so right after the app gets ready when you start it.

Just FYI, this repository is about the Web version of Cozy Drive. The Cozy Desktop repository lives at https://github.com/cozy-labs/cozy-desktop.

**Comment by fred9176** [comment] 2019-11-19 16:18
Hi,

Thank you for your answer. I saw that made as been changed today in 3.16.2-beta2. ;-)

I'll send a report from the app next time I will connect.

**Closed** 2019-11-21 12:39 UTC
