### ISSUE TITLE
Unable to login to mycozy.cloud/auth/login

### ISSUE THREAD

**Issue by mamyn0va** [cozy/cozy-drive#1701] opened 2019-05-21 20:11 UTC
When trying to login to https://borisjamot.mycozy.cloud/auth/login nothing happens and the Console shows the following error:

```log
An invalid form control with name='two-factor-passcode' is not focusable.
```

I checked on the following browsers: 
- waterfox 56.2.8 (64-bit) : KO
- chromium Version 74.0.3729.131 (Official Build) Manjaro Linux (64-bit) : KO
- chrome Version 74.0.3729.157 (Official Build) (64-bit) : KO

It only works on Firefox 66.0.5 (64-bit).

**Comment by nono** [comment] 2019-05-22 06:57
Hello,

do you have some chrome extensions? If yes, you can try to disable them to see if the issue comes from here. I've heard that a few users have issues with password managers, even if I haven't been able to reproduce this myself.

**Comment by mamyn0va** [comment] 2019-05-22 12:23
Hello,

I have lastpass extension. After removing the extension it works fine.

**Comment by nono** [comment] 2019-05-22 12:33
Thanks for the feedback. I will close the issue, as it is a duplicate of https://github.com/cozy/cozy-stack/issues/1905.

**Closed by nono** 2019-05-22 12:33 UTC
