### ISSUE TITLE
Broken image on post-authentication screen

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-drive#1123] opened 2018-08-23 09:17 UTC
See the broken image just below the title:

![screenshot_20180822-232107](https://user-images.githubusercontent.com/3419050/44516689-01e01c00-a6c6-11e8-8ab9-68cdd56da18e.png)

BTW, I don't know why this page was in english whereas everything else was in French…

**Comment by goldoraf** [comment] 2018-08-23 12:50
Pingin @nono 'cause this page comes from the back...

**Comment by nono** [comment] 2018-08-23 16:36
I tried to reproduce this bug, but the logo of Cozy Drive is correctly displayed for me.

**Comment by nicofrand** [comment] 2018-08-23 17:07
Is there an easy way to access this page again (without deleting my account from my phone, etc.) from any browser?

**Comment by nono** [comment] 2018-08-23 17:13
You can use curl to create a client:

```
curl -X POST https://cozy.nicofrand.eu/auth/register -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{"redirect_uris": ["http://localhost"], "software_id": "github.com/example/client", "client_name": "Client", "client_kind": "mobile", "logo_uri": "https://raw.githubusercontent.com/cozy/cozy-drive/master/targets/drive/vendor/assets/oauth-app-icon.png"}'
```

In the response, note the `client_id`. You can open your browser on this URL:

```
https://cozy.nicofrand.eu/auth/authorize?client_id={{client_id}}&state=foo&redirect_uri=http://localhost&response_type=code&scope=io.cozy.files
```

**Comment by Crash--** [comment] 2022-10-05 06:53
Closing this issue since its pretty old.

**Closed by Crash--** 2022-10-05 06:53 UTC
